swagger: "2.0"
info:
  description: "User Management Service. "
  version: "1.0.0"
  title: "Timeslots"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "developer@email.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:5000"
basePath: "/v1"
tags:
- name: "Appointments"
schemes:
- "http"
paths:
  /dentist/timeslots/{did}:
    get:
      tags:
      - "Appointments"
      summary: "Gets the available timeslot of each dentist"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - in: path 
          name: did
          type: string
          required: true
          description: Enter your dentist.
      responses:
        200:
          description: "ok"
        401:
          description: "Not authenticated"
  /dentist/{did}/timeslot/{tid}/cancel:
    put:
      tags:
      - "Appointments"
      summary: "Cancel an timeslot"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: path 
          name: did
          type: string
          required: true
          description: Enter your dentist.
        - in: path 
          name: tid
          type: string
          required: true
          description: Enter your timeslot.
      responses:
        200:
          description: "ok"
        401:
          description: "Not authenticated"
  /dentist/{did}/timeslot/{tid}/reserve:
    get:
      tags:
      - "Appointments"
      summary: "Books an appoinment of a dentist"
      description: ""
      operationId: "userTokenCheck"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: path 
          name: did
          type: string
          required: true
          description: Enter your dentist.
        - in: path 
          name: tid
          type: string
          required: true
          description: Enter your timeslot.
      responses:
        200:
          description: "ok"
        401:
          description: "Not authenticated"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "Auth-Token"
    in: "header"
    
